"""Xero Australia report parsing.

Reads Xero report exports (P&L, balance sheet) into normalised
structures for the lineage pipeline:

- code + tracking-aware: sums rows by (Account, Code), and exposes
  tracking option splits so Tracking Category options can map to
  departments or business units;
- sign-aware: Xero P&L rows are positive for income, negative for
  expenses (standard Xero export), and that convention is preserved;
- GST-aware: Xero reports are GST-exclusive by default. Detects
  GST-INCLUSIVE exports by comparing a control total when provided, or
  by heuristics when not, and refuses to guess silently. Never feed a
  GST-inclusive series into ``pyfpa.au.monthly_gst`` as if exclusive.

This module parses report exports only. It holds no credentials and makes
no network call. Live access is a per-company connector generated by
``openfpa connector-scaffold``, whose credentials come from the host and
are never committed. See docs/recipes/xero-au.md.
"""

from __future__ import annotations

import csv
from collections.abc import Iterable
from pathlib import Path

from pydantic import BaseModel, Field

from pyfpa.io.pl_csv import _parse_amount

_FIXTURES = Path(__file__).resolve().parent / "fixtures"

# Account-code ranges of a standard Australian Xero chart. Used only as a
# heuristic signal; unknown codes never block parsing.
_INCOME_CODES = range(200, 300)
_REVENUE_TYPE_KEYWORDS = ("sales", "revenue", "interest income")


class XeroRow(BaseModel):
    code: str = ""
    account: str
    amount: float
    tracking_option: str = ""  # empty = untracked / no category assigned


class XeroReport(BaseModel):
    rows: list[XeroRow] = Field(default_factory=list)
    gst_inclusive: bool | None = None  # None = undetermined; see detect_gst_inclusive

    def by_account(self) -> dict[str, float]:
        """{account: amount} summed across codes and tracking options."""
        totals: dict[str, float] = {}
        for row in self.rows:
            totals[row.account] = totals.get(row.account, 0.0) + row.amount
        return totals

    def by_tracking(self) -> dict[str, dict[str, float]]:
        """{tracking_option: {account: amount}} for department mapping."""
        splits: dict[str, dict[str, float]] = {}
        for row in self.rows:
            key = row.tracking_option or "(untracked)"
            splits.setdefault(key, {})
            splits[key][row.account] = splits[key].get(row.account, 0.0) + row.amount
        return splits

    def unmapped_tracking(self, allowed: Iterable[str] = ()) -> list[str]:
        """Tracking options present in the report but not in `allowed`.

        `allowed` is the tracking category's mapped option list, supplied
        by the caller from generate-time config; the default (nothing
        mapped yet) returns every option in the file. Untracked rows are
        not options - surface those from ``by_tracking()['(untracked)']``.
        """
        return sorted({r.tracking_option for r in self.rows} - set(allowed) - {""})


def read_xero_report(path: str | Path) -> XeroReport:
    """Parse a Xero CSV export into an XeroReport.

    Expected columns: Code, Account, Amount; optional Tracking Option.
    Xero omits Code on some report layouts; empty codes are allowed.
    """
    p = Path(path)
    if not p.exists():
        raise FileNotFoundError(f"Xero report not found: {p}")
    rows: list[XeroRow] = []
    with p.open(newline="") as f:
        reader = csv.DictReader(f)
        fields = reader.fieldnames or []
        if "Account" not in fields or "Amount" not in fields:
            raise ValueError(
                f"expected columns 'Account' and 'Amount', got {fields}"
            )
        for raw in reader:
            account = (raw.get("Account") or "").strip()
            if not account:
                continue
            rows.append(
                XeroRow(
                    code=(raw.get("Code") or "").strip(),
                    account=account,
                    amount=_parse_amount(raw.get("Amount")),
                    tracking_option=(raw.get("Tracking Option") or "").strip(),
                )
            )
    if not rows:
        raise ValueError(f"no rows parsed from {p}")
    return XeroReport(rows=rows)


def detect_gst_inclusive(
    report: XeroReport, control_total: float | None = None
) -> bool | None:
    """Best-effort check that a revenue series is GST-EXCLUSIVE.

    Returns True when the series looks GST-INCLUSIVE (danger), False
    when it looks exclusive (safe), None when undetermined. With a
    `control_total` (the entity's known GST-exclusive revenue for the
    period) the check compares tolerance: within 1% -> exclusive, within
    1% of 1.1x -> inclusive.

    Heuristic without a control: an export whose income-account amounts
    are all divisible cleanly by 1.1 to 4+ significant figures is
    probably exclusive already (someone divided by 11); raw trading
    totals rarely are. Weak signal - used only to force a question,
    never to auto-tag.
    """
    income = [
        r.amount
        for r in report.rows
        if r.amount > 0
        and (
            (r.code.isdigit() and int(r.code) in _INCOME_CODES)
            or any(k in r.account.casefold() for k in _REVENUE_TYPE_KEYWORDS)
        )
    ]
    if not income:
        return None
    if control_total is not None and control_total > 0:
        total = sum(income)
        if abs(total - control_total) / control_total < 0.01:
            return False
        if abs(total - control_total * 1.1) / (control_total * 1.1) < 0.01:
            return True
        return None
    clean = sum(
        1 for a in income if abs(round(a / 1.1, 2) * 1.1 - a) < 0.005
    )
    if clean == len(income):
        return False
    return None


def from_xero(
    *, fixture: str | Path | None = None, balance_sheet: bool = False
) -> dict[str, float]:
    """Return a normalised {account: amount} table from a Xero export.

    Mirrors ``from_quickbooks``/``from_netsuite``: reads a CSV export,
    falling back to the bundled fixture. There is no live path here; a
    per-company connector supplies one.
    """
    path = fixture or (_FIXTURES / ("xero_bs_au.csv" if balance_sheet else "xero_pl_au.csv"))
    return read_xero_report(path).by_account()
